server:
  port: 8012     #端口
  servlet:
    context-path: ${spring.application.name}  #上下文
    session:
      timeout: 900
  tomcat:
    max-threads: 400
    uri-encoding: UTF-8

spring:
  application:
    name: /task-web                         #应用上下文
  profiles:
    #    active: telecom_test               # 启用哪个配置环境
    active: mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 当前数据源操作类型
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall
#      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
#      stat-view-servlet:
#        login-username: admin
#        login-password: 123456
#        reset-enable: false
#        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
#      web-stat-filter:
        # 添加过滤规则
#        url-pattern: /*
        # 忽略过滤格式
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
## templates文件夹的路径
#  thymeleaf:
#    prefix: classpath:/templates/
#  # templates中的所有文件后缀名，如/templates/main.html
#    suffix: .html

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#  redis:
#    database: 0
#    password: qazwsx456
#    jedis:
#      pool:
#        max-active: 800
#        max-idle: 800
#        min-idle: 10
#        max-wait: -1




---
# mysql 环境
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver      # mysql驱动包
    # 数据库地址
    url: jdbc:mysql://127.0.0.1:3306/wangshen?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#  redis:
#    sentinel:
#      master: aimaster
#      nodes: 10.20.16.70:11379

---
# telecom 测试环境
spring:
  profiles: telecom_test
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver      # oracle驱动包
#     #数据库名称
#    url: jdbc:oracle:thin:@132.228.187.253:1621:apprc
#    username: apprc_user_test
#    password: b$_FX@Wv123
#  redis:
#    sentinel:
#      master: aimaster
#      nodes: 132.228.187.252:11379